# Generated by Django 5.0 on 2025-12-26 12:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0004_botapikey'),
        ('chat', '0001_initial'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Дата статистики')),
                ('messages_received', models.IntegerField(default=0, help_text='Получено сообщений от пользователей')),
                ('messages_sent', models.IntegerField(default=0, help_text='Отправлено ответов')),
                ('unique_users', models.IntegerField(default=0, help_text='Уникальные пользователи за день')),
                ('new_users', models.IntegerField(default=0, help_text='Новые пользователи')),
                ('returning_users', models.IntegerField(default=0, help_text='Вернувшиеся пользователи')),
                ('tokens_used', models.IntegerField(default=0, help_text='Использовано токенов')),
                ('avg_response_time_ms', models.IntegerField(default=0, help_text='Среднее время ответа (мс)')),
                ('rag_queries', models.IntegerField(default=0, help_text='Запросов с использованием RAG')),
                ('positive_feedback', models.IntegerField(default=0, help_text='Положительные оценки (👍)')),
                ('negative_feedback', models.IntegerField(default=0, help_text='Отрицательные оценки (👎)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Bot Analytics',
                'verbose_name_plural': 'Bot Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['bot', 'date'], name='analytics_b_bot_id_67d016_idx'), models.Index(fields=['date'], name='analytics_b_date_f9579a_idx')],
                'unique_together': {('bot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('received', 'Message Received'), ('sent', 'Message Sent'), ('error', 'Error')], max_length=20)),
                ('message_length', models.IntegerField(default=0, help_text='Длина сообщения (символов)')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Время генерации ответа (мс)', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Использовано токенов', null=True)),
                ('used_rag', models.BooleanField(default=False, help_text='Использовался ли RAG')),
                ('error_message', models.TextField(blank=True, help_text="Описание ошибки (если event_type='error')")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='bots.bot')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatsession')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Message Event',
                'verbose_name_plural': 'Message Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bot', 'timestamp'], name='analytics_m_bot_id_1b5ab5_idx'), models.Index(fields=['event_type', 'timestamp'], name='analytics_m_event_t_9a8e83_idx'), models.Index(fields=['telegram_user', 'timestamp'], name='analytics_m_telegra_2671ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата использования')),
                ('input_tokens', models.IntegerField(default=0, help_text='Входные токены (prompt)')),
                ('output_tokens', models.IntegerField(default=0, help_text='Выходные токены (response)')),
                ('total_tokens', models.IntegerField(default=0, help_text='Всего токенов')),
                ('estimated_cost_cents', models.IntegerField(default=0, help_text='Примерная стоимость в центах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['bot', 'date'], name='analytics_t_bot_id_f79841_idx')],
                'unique_together': {('bot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.CharField(choices=[('positive', '👍 Helpful'), ('negative', '👎 Not Helpful')], max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Дополнительный комментарий от пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='bots.bot')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.chatmessage')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot', 'created_at'], name='analytics_u_bot_id_5d5694_idx'), models.Index(fields=['feedback'], name='analytics_u_feedbac_7bbe81_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRetention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_date', models.DateField(help_text='Дата первого использования бота (cohort)')),
                ('day_1_retained', models.IntegerField(default=0, help_text='Пользователей, вернувшихся на 1-й день')),
                ('day_7_retained', models.IntegerField(default=0, help_text='Пользователей, вернувшихся на 7-й день')),
                ('day_30_retained', models.IntegerField(default=0, help_text='Пользователей, вернувшихся на 30-й день')),
                ('total_users_in_cohort', models.IntegerField(default=0, help_text='Всего пользователей в cohort')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_cohorts', to='bots.bot')),
            ],
            options={
                'verbose_name': 'User Retention',
                'verbose_name_plural': 'User Retention',
                'ordering': ['-cohort_date'],
                'indexes': [models.Index(fields=['bot', 'cohort_date'], name='analytics_u_bot_id_d8089f_idx')],
                'unique_together': {('bot', 'cohort_date')},
            },
        ),
    ]
