# Generated by Django 5.2.8 on 2026-02-10 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_add_analytics_models"),
        ("bots", "0008_add_webhook_monitoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("received", "Webhook Received"),
                            ("processed", "Update Processed"),
                            ("error", "Processing Error"),
                            ("response_sent", "Response Sent"),
                            ("retry", "Delivery Retry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("update_id", models.BigIntegerField(help_text="Telegram update_id")),
                (
                    "webhook_delivery_time",
                    models.DateTimeField(help_text="Когда webhook был получен от Telegram"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(blank=True, help_text="Время обработки (мс)", null=True),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID", max_length=255, null=True
                    ),
                ),
                (
                    "response_sent",
                    models.BooleanField(default=False, help_text="Был ли отправлен ответ"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Время отправки ответа (мс)", null=True
                    ),
                ),
                (
                    "error_type",
                    models.CharField(blank=True, help_text="Тип ошибки", max_length=100),
                ),
                ("error_message", models.TextField(blank=True, help_text="Сообщение об ошибке")),
                (
                    "retry_count",
                    models.IntegerField(default=0, help_text="Количество попыток повтора"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP адрес запроса", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User Agent")),
                (
                    "telegram_signature_valid",
                    models.BooleanField(default=True, help_text="Валидна ли подпись Telegram"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["bot", "timestamp"], name="analytics_w_bot_id_1364bb_idx"),
                    models.Index(
                        fields=["event_type", "timestamp"], name="analytics_w_event_t_65508f_idx"
                    ),
                    models.Index(
                        fields=["status", "timestamp"], name="analytics_w_status_e1d55c_idx"
                    ),
                    models.Index(fields=["update_id"], name="analytics_w_update__68123a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(help_text="Дата метрик")),
                ("hour", models.IntegerField(default=0, help_text="Час (0-23)")),
                (
                    "requests_received",
                    models.IntegerField(default=0, help_text="Получено webhook запросов"),
                ),
                (
                    "requests_processed",
                    models.IntegerField(default=0, help_text="Успешно обработано"),
                ),
                (
                    "requests_failed",
                    models.IntegerField(default=0, help_text="Неуспешных запросов"),
                ),
                (
                    "avg_processing_time_ms",
                    models.IntegerField(default=0, help_text="Среднее время обработки (мс)"),
                ),
                (
                    "p95_processing_time_ms",
                    models.IntegerField(default=0, help_text="95-й перцентиль времени обработки"),
                ),
                (
                    "p99_processing_time_ms",
                    models.IntegerField(default=0, help_text="99-й перцентиль времени обработки"),
                ),
                ("responses_sent", models.IntegerField(default=0, help_text="Отправлено ответов")),
                (
                    "avg_response_time_ms",
                    models.IntegerField(default=0, help_text="Среднее время ответа (мс)"),
                ),
                (
                    "signature_validation_failures",
                    models.IntegerField(default=0, help_text="Ошибок валидации подписи"),
                ),
                ("processing_errors", models.IntegerField(default=0, help_text="Ошибок обработки")),
                ("timeout_errors", models.IntegerField(default=0, help_text="Таймаутов")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_metrics",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Metrics",
                "verbose_name_plural": "Webhook Metrics",
                "ordering": ["-date", "-hour"],
                "indexes": [
                    models.Index(
                        fields=["bot", "date", "hour"], name="analytics_w_bot_id_be6c45_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_w_date_7d1a52_idx"),
                ],
                "unique_together": {("bot", "date", "hour")},
            },
        ),
    ]
