# Generated by Django 5.0 on 2025-11-22 19:51

import apps.knowledge.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.knowledge.models.document_upload_path)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Word Document'), ('md', 'Markdown')], max_length=10)),
                ('size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('indexing', 'Indexing'), ('ready', 'Ready'), ('error', 'Error')], default='indexing', max_length=20)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['bot', 'status'], name='knowledge_d_bot_id_bc3145_idx'), models.Index(fields=['upload_date'], name='knowledge_d_upload__63f81e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Text Snippet',
                'verbose_name_plural': 'Text Snippets',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['bot'], name='knowledge_t_bot_id_7bb315_idx'), models.Index(fields=['updated_at'], name='knowledge_t_updated_e2919e_idx')],
            },
        ),
    ]
