# Generated by Django 5.0 on 2025-12-25 13:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botapikey'),
        ('knowledge', '0002_textsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsnippet',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Embedding vector for RAG search', null=True),
        ),
        migrations.AddIndex(
            model_name='textsnippet',
            index=models.Index(fields=['bot', 'updated_at'], name='knowledge_t_bot_id_78a888_idx'),
        ),
    ]
