# Generated by Django 5.0 on 2025-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botapikey'),
        ('knowledge', '0003_textsnippet_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name of the document', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', help_text='Processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Word Document'), ('md', 'Markdown')], default='txt', help_text='File type', max_length=10),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['bot', 'status'], name='knowledge_d_bot_id_bc3145_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='knowledge_d_uploade_4894cf_idx'),
        ),
    ]
