# Generated by Django 5.0 on 2025-11-22 19:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='draft', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='gemini', max_length=20)),
                ('temperature', models.FloatField(default=0.7)),
                ('system_instruction', models.TextField(blank=True)),
                ('thinking_budget', models.IntegerField(blank=True, null=True)),
                ('telegram_token', models.CharField(blank=True, max_length=200)),
                ('avatar', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='bots_bot_owner_i_34b8d2_idx'), models.Index(fields=['created_at'], name='bots_bot_created_996935_idx'), models.Index(fields=['status'], name='bots_bot_status_7ce791_idx')],
            },
        ),
    ]
