# Generated by Django 5.0 on 2025-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='default_inline_keyboard',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bot',
            name='help_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bot',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
