# Generated by Django 5.0 on 2025-12-25 11:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_encrypt_telegram_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this API key', max_length=100)),
                ('key', models.CharField(db_index=True, help_text='API key (hashed)', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of key for identification', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Bot API Key',
                'verbose_name_plural': 'Bot API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='bots_botapi_key_c414f5_idx'), models.Index(fields=['bot', 'is_active'], name='bots_botapi_bot_id_3fb07d_idx')],
            },
        ),
    ]
