# Generated by Django 5.0 on 2025-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
