# Generated by Django 5.2.8 on 2026-02-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0007_add_delivery_mode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bot",
            new_name="bots_bot_deliver_783646_idx",
            old_name="bots_deliver_mode_idx",
        ),
    ]
