# Generated by Django 5.0 on 2026-01-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0005_bot_webhook_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Command name without / (e.g., start, help)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Description"),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("ai", "AI ответ"),
                            ("form", "Форма"),
                            ("menu", "Меню"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Response type",
                    ),
                ),
                (
                    "text_response",
                    models.TextField(
                        blank=True,
                        help_text="For TEXT type: the message to send",
                        verbose_name="Text response",
                    ),
                ),
                (
                    "ai_prompt_override",
                    models.TextField(
                        blank=True,
                        help_text="For AI type: override system prompt",
                        verbose_name="AI prompt override",
                    ),
                ),
                (
                    "form_id",
                    models.CharField(
                        blank=True,
                        help_text="For FORM type: form identifier",
                        max_length=255,
                        verbose_name="Form ID",
                    ),
                ),
                (
                    "menu_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For MENU type: inline keyboard configuration",
                        verbose_name="Menu config",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="For sorting (higher first)", verbose_name="Priority"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="bots.bot",
                        verbose_name="Bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Command",
                "verbose_name_plural": "Commands",
                "db_table": "commands_command",
                "ordering": ["-priority", "name"],
                "unique_together": {("bot", "name")},
            },
        ),
    ]
