# Generated by Django 5.2.8 on 2025-12-26 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0005_bot_webhook_secret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=150)),
                ("model_id", models.CharField(max_length=100)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("chat", "Chat/Conversation"),
                            ("reasoning", "Advanced Reasoning"),
                            ("fast", "Fast Response"),
                            ("vision", "Vision/Images"),
                            ("code", "Code Generation"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("max_tokens", models.IntegerField(default=8192)),
                (
                    "input_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "output_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("supports_thinking", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "ordering": ["provider", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("base_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("improve_instruction", "Improve with AI"),
                            ("generate_content", "Generate with AI"),
                            ("chat_response", "Chat Response"),
                            ("transcription", "Audio Transcription"),
                            ("file_processing", "File Processing"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_features",
                        to="ai_settings.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Feature",
                "verbose_name_plural": "AI Features",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="ai_settings.aiprovider",
            ),
        ),
        migrations.CreateModel(
            name="AIUsageLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("plan", models.CharField(max_length=20)),
                ("max_uses", models.IntegerField(default=1)),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("is_unlimited", models.BooleanField(default=False)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="ai_settings.aifeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Limit",
                "verbose_name_plural": "AI Usage Limits",
                "ordering": ["plan", "feature"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cost_cents", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="bots.bot",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="ai_settings.aifeature",
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="ai_settings.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["is_active", "is_default"], name="ai_settings_is_acti_77ad58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "model_id")},
        ),
        migrations.AlterUniqueTogether(
            name="aiusagelimit",
            unique_together={("plan", "feature")},
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["user", "feature", "created_at"], name="ai_settings_user_id_ad6b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(fields=["created_at"], name="ai_settings_created_216d69_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(fields=["success"], name="ai_settings_success_a10436_idx"),
        ),
    ]
