# Generated by Django 5.0 on 2025-11-22 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['bot', 'status'], name='telegram_te_bot_id_ca72bf_idx'), models.Index(fields=['telegram_id'], name='telegram_te_telegra_000672_idx'), models.Index(fields=['last_active'], name='telegram_te_last_ac_906d5d_idx')],
                'unique_together': {('telegram_id', 'bot')},
            },
        ),
    ]
