# Generated by Django 5.0 on 2025-12-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'timestamp'], name='chat_chatme_role_282dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='chat_chatme_timesta_f0eb7d_idx'),
        ),
    ]
